version: "2"
services:

  fulfillment:
    image: openlmis/dev:5.2
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - '.:/app'
      - 'gradlecache:/gradle'
  db:
    ports:
      - "5432"

volumes:
  gradlecache:
    external: false
